function net = iLab_simplenn_addlayer_block(net, name, opts)
    val_block_param = struct( ...
                'h',            3, ...
                'w',            3, ...
                'in',           48, ...
                'out',          96, ...
                'stride',       1, ...
                'pad',          0, ...
                'filter',       [], ...
                'bias',         [], ...
                'learningRate', [1 2], ...
                'weightDecay',  [1 0], ...
                'scale',            1, ...             
                'weightInitMethod', 'gaussian');
     
    opts = iLab_arg2struct(opts);
    opts = iLab_simplenn_validateBlockParam(opts);  
    
    h   = opts.h; 
    w   = opts.w; 
    in  = opts.in; 
    out = opts.out;
    stride = opts.stride; 
    pad = opts.pad;
    filter = opts.filter;
    bias = opts.bias;
    learningRate = opts.learningRate;
    weightDecay = opts.weightDecay;
    
    if isempty(filter)     
        filter = iLab_nn_initWeight(opts, h, w, in, out, 'single');
    end
    
    if isempty(bias)
       bias = zeros(out,1, 'single');
    end
    
    net.layers{end+1} = struct('type', 'conv', 'name', sprintf('%s', name), ...
                               'weights', {{filter, bias}}, ...
                               'stride', stride, ...
                               'pad', pad, ...
                               'learningRate', learningRate, ...
                               'weightDecay', weightDecay) ;


end