function val_param = iLab_dagnn_validateConvLayerParam(param)
   
    if nargin == 0 || ~exist('param', 'var') || isempty(param)
        val_param = struct( ...
                    'size',         [3 3 48 96], ...
                    'stride',       1, ...
                    'pad',          0, ...
                    'filter',       [], ...
                    'bias',         [], ...
                    'fname',        '',     ...
                    'bname',        '',     ...
                    'learningRate', [1 2], ...
                    'weightDecay',  [1 0], ...
                    'scale',            1, ...             
                    'weightInitMethod', 'gaussian');
                
        return;
    end
    
    param = iLab_arg2struct(param);
    val_param = param;
    fields = {
    'size'    'stride'    'pad'    ...
    'filter'    'bias'  'fname', 'bname',   'learningRate'    'weightDecay' ...
    'scale'    'weightInitMethod'};
    values = {[3 3 48 96] 1 0 ...
              [] [] '' '' [1 2] [1 0] ...
              1,'gaussian'};
            
    for f=1:numel(fields)
        if ~isfield(val_param, fields{f})
            val_param.(fields{f}) = values{f};
        end
    end    

    
    
end