function net = iLab_simplenn_addlayer_pooling(net, name, opts)
    
    opts = iLab_arg2struct(opts);
    opts = iLab_simplenn_validatePoolingParam(opts);
    method  = opts.method;
    pool    = opts.pool;
    stride  = opts.stride;
    pad     = opts.pad;
    
    net.layers{end+1} = struct('type', 'pool', ...
                               'name',      name, ...
                               'method',    method, ...
                               'pool',      pool, ...
                               'stride',    stride, ...
                               'pad',       pad) ;

    % e.g.
    %{
    net.layers{end+1} = struct('type', 'pool', 'name', 'pool1', ...
                       'method', 'max', ...
                       'pool', [3 3], ...
                       'stride', 2, ...
                       'pad', 0) ;
	%}
end